domain: modularscript.github.
url: https://modularscript.github.io
title: Modular Script
baseurl:
email: your-email@example.com
description: Dive into the world of coding and technical exploration with us. Whether you’re a seasoned developer or just starting out, our site offers a treasure trove of scripts, coding tutorials, and insights into various technical interests. Join our community of tech enthusiasts and elevate your skills to the next level. Let’s code, learn, and innovate together!
twitter_username: jekyllrb
github_username:  modularscript

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
